app/controllers/team.py
from app.database import create_connection, close_connection
from flask import jsonify
from datetime import datetime


class Team:
    def __init__(self, nome, descricao, criador_id):
        self.nome = nome
        self.descricao = descricao
        self.criador_id = criador_id

    def criar_equipe(self):
        conexao = create_connection()

        if conexao:
            cursor = conexao.cursor()
            try:
                #! Inserindo dados na Tabela equipes
                sql = "INSERT INTO equipes (nome, descricao, criador_id) VALUES (%s, %s, %s)"
                values = (self.nome, self.descricao, self.criador_id)
                cursor.execute(sql, values)
                conexao.commit()

                # *Obter Id da Equipe recem criada
                equipe_id = cursor.lastrowid

                #!Inserir o criador da equipe na tabela equipe_membros

                sql_membro = "INSERT INTO equipe_membros (equipe_id, user_id, cargo) VALUES (%s, %s, %s)"
                values_membro = (equipe_id, self.criador_id, "administrador")
                cursor.execute(sql_membro, values_membro)
                conexao.commit()

                print(f"Equipe {self.nome} cadastrada com sucesso.")

            except Exception as e:
                print(f"Erro ao criar equipe: {e}")
            finally:
                cursor.close()
                close_connection(conexao)
                print("A Conexão com o banco de dados foi encerrada.")


    @staticmethod
    def listar_equipes(user_id):
        conexao = create_connection()

        if conexao:
            cursor = conexao.cursor()

            sql = """
                SELECT 
                    equipes.id, 
                    equipes.nome, 
                    equipes.descricao, 
                    equipes.criado,
                    (SELECT COUNT(*) FROM equipe_membros WHERE equipe_membros.equipe_id = equipes.id) AS qtd_membros,
                    (SELECT COUNT(*) FROM projetos WHERE projetos.equipe_id = equipes.id) AS qtd_projetos,
                    equipe_membros.cargo
                FROM equipes
                JOIN equipe_membros ON equipes.id = equipe_membros.equipe_id
                WHERE equipe_membros.user_id = %s
                GROUP BY equipes.id, equipe_membros.cargo
            """

            try:
                cursor.execute(sql, (user_id,))
                equipes = cursor.fetchall()
                if equipes:
                    return equipes
                else:
                    return None
            except Exception as e:
                print(f"Erro ao listar equipes: {e}")
                return None
            finally:
                close_connection(conexao)



    @staticmethod
    def listar_membros(equipe_id):
        conexao = create_connection()

        if conexao:
            cursor = conexao.cursor()

            sql = """
                SELECT 
                    usuarios.id,
                    usuarios.nome, 
                    usuarios.username, 
                    usuarios.email, 
                    equipe_membros.cargo
                FROM equipe_membros
                JOIN usuarios ON equipe_membros.user_id = usuarios.id
                WHERE equipe_membros.equipe_id = %s
            """

            try:
                cursor.execute(sql, (equipe_id,))
                membros = cursor.fetchall()
                if membros:
                    return membros
                else:
                    return None
            except Exception as e:
                print(f"Erro ao listar membros da equipe: {e}")
                return None
            finally:
                cursor.close()
                close_connection(conexao)

    # Função para alterar o cargo de um membro
    @staticmethod
    def atualizar_cargo(user_id, cargo, equipe_id):
        conexao = create_connection()

        if conexao:
            cursor = conexao.cursor()
            try:
                # Atualiza o cargo do membro na tabela equipe_membros
                sql = "UPDATE equipe_membros SET cargo = %s WHERE user_id = %s AND equipe_id = %s"
                values = (cargo, user_id, equipe_id)
                cursor.execute(sql, values)
                conexao.commit()

                print(f"Cargo do membro com ID {user_id} alterado para {cargo}.")
                return True  # Indica sucesso

            except Exception as e:
                print(f"Erro ao alterar o cargo: {e}")
                return False  # Indica falha
            finally:
                cursor.close()
                close_connection(conexao)

    # Função para adicionar mensagem

    @staticmethod
    def adicionar_mensagem(user_id, equipe_id, mensagem):
        try:
            # Conexão com o banco de dados
            conexao = create_connection()
            cursor = conexao.cursor()

            # Comando SQL para inserir a mensagem
            sql = """
                INSERT INTO mensagens (user_id, equipe_id, mensagem, enviado_em)
                VALUES (%s, %s, %s, NOW())
            """
            cursor.execute(sql, (user_id, equipe_id, mensagem))

            # Commit para salvar a mensagem no banco
            conexao.commit()

            print(f"Mensagem enviada para o time {equipe_id} pelo usuário {user_id}.")
            return True  # Sucesso

        except Exception as e:
            print(f"Erro ao adicionar mensagem: {e}")
            return False  # Falha

        finally:
            # Fechar cursor e conexão
            if cursor:
                cursor.close()
            if conexao:
                close_connection(conexao)

    @staticmethod
    def listar_mensagens(equipe_id):
        mensagens = None
        try:
            conexao = create_connection()
            if conexao:
                cursor = conexao.cursor()
                sql = """
                    SELECT mensagens.*, usuarios.nome 
                    FROM mensagens 
                    JOIN usuarios ON mensagens.user_id = usuarios.id 
                    WHERE mensagens.equipe_id = %s
                    ORDER BY enviado_em ASC
                """  # Remover a vírgula após a string
                cursor.execute(sql, (equipe_id,))
                mensagens = cursor.fetchall()
                

                if mensagens:
                    print("mensagens carregadas")
                    return mensagens
        except Exception as e:
            print(f"Error ao listar mensagens {e}")
        finally:
            close_connection(conexao)

app/routes/routes.py
from flask import Blueprint
from app.controllers.views import *

bp = Blueprint("main", __name__)

#! Index
@bp.route("/")
@bp.route("/index")
def index_route():
    return index()

#! Register
@bp.route("/register", methods=["GET", "POST"])
def register_route():
    return register()

#! Login
@bp.route("/login", methods=["GET", "POST"])
def login_route():
    return login()

#! Logout
@bp.route("/logout")
def logout_route():
    return logout()

#! Dashboard
@bp.route("/dashboard", methods=["GET"])
def dashboard_route():
    return dashboard()


#! Tela da Equipe
@bp.route("/team_vision/<int:team_id>")
def team_vision_route(team_id):
    return team_vision(team_id)
# equipe
@bp.route("/teams")
def teams_route():
    return teams()

#! Team
@bp.route("/create_team", methods=["GET", "POST"])
def create_team_route():
    return create_team()

#! Convidar Membros para o time
@bp.route("/invite_to_team/<int:team_id>", methods=["POST"])
def invite_to_team_route(team_id):
    return invite_to_team(team_id)

#! Aceitar o convite para equipe
@bp.route("/accept_invite", methods=["POST"])
def accept_invite_route():
    return accept_invite()

#! Recusar o convite para equipe
@bp.route("/decline_invite", methods=["POST"])
def decline_invite_route():
    return decline_invite()

#! Recusar o convite para equipe
@bp.route("/alterar_cargo", methods=["POST"])
def alterar_cargo_route():
    return alterar_cargo()

#! Enviar Mensagem
@bp.route("/adicionar_mensagem/<int:team_id>", methods=["POST"])
def adicionar_mensagem_route(team_id):
    return adicionar_mensagem(team_id)

@bp.route("/criar_projeto/<int:team_id>", methods=["GET", "POST"])
def criar_projeto_route(team_id):
    return create_project(team_id)

@bp.route('/criar_tarefa', methods=['POST'])
def criar_tarefa_route():
    return criar_tarefa()

app/templates/team/create_project.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <title>DreamTeam - Criar equipe</title>
  </head>
  <body>
    {% include 'menu.html' %}

    <div class="container-top">
      <a href="{{ url_for('main.team_vision_route', team_id=team_id) }}"
        ><button class="button">Cancelar e voltar</button></a>
        <div class="flash-container">
          <!-- Mensagens Flash -->
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %}
          <ul class="flashes">
            {% for category, message in messages %}
            <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
          </ul>
          {% endif %} {% endwith %}
        </div>
    </div>

    <div class="container">
      <div class="form-box">
        <form
          class="formulario"
          action="{{ url_for('main.criar_projeto_route', team_id=team_id) }}"
          method="POST"
          enctype="multipart/form-data"
        >
          <div class="title">Crie um novo projeto</div>
          <div class="input-group">
            <div class="input-box">
              <input
                type="text"
                id="equipe"
                name="nome"
                placeholder="Nome do projeto:"
                required
                maxlength="32"
              />
            </div>
            <div class="input-box">
              <input
                type="text"
                id="descricao"
                name="descricao"
                placeholder="Descrição do Projeto:"
              />
            </div>
            <div class="input-box">
              <label for="foto" class="custom-file-label">
                <img src="static/icons/upload.svg" height="20" alt="" />Enviar
                Foto da Projeto</label
              >
              <input
                type="file"
                id="foto"
                name="foto"
                placeholder="Foto da equipe"
                class="custom-file-input"
              />
            </div>
          </div>
          <div class="button-box">
            <button class="button">Criar Projeto</button>
          </div>
        </form>
      </div>
    </div>
  </body>

  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</html>

app/templates/team/create_team.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <title>DreamTeam - Criar equipe</title>
  </head>
  <body>
    {% include 'menu.html' %}

    <div class="container-top">
      <a href="/teams"><button class="button">Cancelar e voltar</button></a>
    </div>
    <div class="container">
      <div class="form-box">
        <form
          class="formulario"
          action="/create_team"
          method="POST"
          enctype="multipart/form-data"
        >
          <div class="title">Crie uma nova equipe</div>
          <!-- Mensagens Flash -->
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %}
          <ul class="flashes">
            {% for category, message in messages %}
            <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
          </ul>
          {% endif %} {% endwith %}
          <div class="input-group">
            <div class="input-box">
              <input
                type="text"
                id="equipe"
                name="equipe"
                placeholder="Nome da Equipe:"
                required
                maxlength="32"
              />
            </div>
            <div class="input-box">
              <input
                type="text"
                id="descricao"
                name="descricao"
                placeholder="Descrição da Equipe:"
              />
            </div>
            <div class="input-box">
              <label for="foto" class="custom-file-label">
                <img src="static/icons/upload.svg" height="20" alt="" />Enviar
                Foto da equipe</label
              >
              <input
                type="file"
                id="foto"
                name="foto"
                placeholder="Foto da equipe"
                class="custom-file-input"
              />
            </div>
          </div>
          <div class="button-box">
            <button class="button">Criar Equipe</button>
          </div>
        </form>
      </div>
    </div>
  </body>

  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</html>

app/templates/team/team_vision.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <title>DreamTeam - {{equipe[1]}}</title>
  </head>
  <body>
    {% include 'menu.html' %}

    <div class="container-top">
      <a href="/teams"><button class="button">Voltar</button></a>
      <div class="flash-container">
        <!-- Mensagens Flash -->
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %}
        <ul class="flashes">
          {% for category, message in messages %}
          <li class="{{ category }}">{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %} {% endwith %}
      </div>
    </div>

    <div class="container-team-vision">
      <!-- Menu Lateral -->
      <aside class="sidebar">
        <h2>{{equipe[1]}}</h2>
        <ul>
          <li data-section="team-details">Detalhes da Equipe</li>
          <li data-section="projects">Projetos</li>
          <li data-section="chat">Chat</li>
          <li data-section="references">Murais de Referências</li>
          <li data-section="members">Membros</li>
        </ul>
      </aside>

      <!-- Conteúdo Principal -->
      <main class="content">
        <!-- Detalhes -->
        <section id="team-details" class="hidden">
          <h1>{{equipe[1]}}</h1>
          <h2>{{equipe[2]}}</h2>
          <h3>Criado: {{equipe[5]}}</h3>
        </section>

        <!-- Projetos -->
        <section id="projects" class="hidden">
          {% if cargo_user != 'membro' %}
          <a
            href="{{ url_for('main.criar_projeto_route', team_id=equipe[0]) }}"
          >
            <button class="button">Criar projeto</button>
          </a>
          {% endif %}

          <h1>Projetos</h1>

          {% if projetos %}
          <div class="projects-container">
            {% for projeto in projetos %}
            <div class="project-card">
              <h2>{{ projeto[1] }}</h2>
              <h4>Descrição:</h4>
              <h5>{{ projeto[2] }}</h5>
              <h4>Status:</h4>
              <h5>{{ projeto[3] }}</h5>

              {% if tarefas %} 
              {% for tarefa in tarefas %} 
              {% if tarefa.projeto_id == projeto[0] %}
              <h3>{{ tarefa.nome }}</h3>
              <h3>{{ tarefa.prazo }}</h3>
              {% endif %} {% endfor %} {% else %}
              <h2>Não há tarefas cadastradas</h2>
              {% endif %}

              <form
                action="{{ url_for('main.criar_tarefa_route') }}"
                method="POST"
              >
                <div class="input-group">
                  <div class="input-boxes">
                    <label for="nome_tarefa">Nome da Tarefa:</label>
                    <input
                      type="text"
                      name="nome_tarefa"
                      id="nome_tarefa"
                      required
                    />
                  </div>
                  <div class="input-boxes">
                    <label for="prazo_tarefa">Prazo:</label>
                    <input
                      type="date"
                      name="prazo_tarefa"
                      id="prazo_tarefa"
                      required
                    />
                    <input
                      type="hidden"
                      name="projeto_id"
                      value="{{ projeto[0] }}"
                    />
                    <input type="hidden" name="team_id" value="{{ team_id }}" />
                  </div>
                </div>
                <button type="submit" class="button">Adicionar Tarefa</button>
              </form>
            </div>
            {% endfor %}
          </div>
          {% else %}
          <p>
            Esse time ainda não criou nenhum projeto. Crie agora um novo
            projeto!
          </p>
          {% endif %}
        </section>

        <!-- Chat -->
        <section id="chat" class="hidden">
          <h1>Chat</h1>

          <div id="chat-container" class="chat-container">
            {% if mensagens %}
            <ul>
              {% for mensagem in mensagens %}
              <li>
                <div
                  class="mensagem {% if mensagem[2] == user_id %}my_mensagem{% else %}mensagem-equipe{% endif %}"
                >
                  <p>{{ mensagem[5] }}:</p>
                  <!-- Nome do usuário -->
                  <strong>{{ mensagem[3] }}</strong>
                  <p>{{ mensagem[4] }}:</p>
                  <!-- data da mensagem -->
                </div>
              </li>
              {% endfor %}
            </ul>
            {% else %}
            <p>Envie uma mensagem para a sua equipe.</p>
            {% endif %}
          </div>
          <form
            action="{{ url_for('main.adicionar_mensagem_route', team_id=equipe[0]) }}"
            method="POST"
          >
            <input type="hidden" name="equipe_id" value="{{ equipe[0] }}" />
            <textarea
              class="textarea"
              name="mensagem"
              placeholder="Digite sua mensagem..."
            ></textarea>
            <button class="button-edit" type="submit">Enviar</button>
          </form>
        </section>

        <!-- Murais -->
        <section id="references" class="hidden">
          <h1>Murais</h1>
        </section>

        <!-- Membros -->
        <section id="members" class="hidden">
          <h1>Membros</h1>
          {% if cargo_user != "membro" %}
          <button class="button" id="button-form" onclick="show_form()">
            Convidar Membros
          </button>
          {% endif %}
          <div class="members-team-container">
            {% for membro in membros %}
            <div class="members-team">
              <h3>Nome: {{ membro[1] }}</h3>
              <h4>{{ membro[2] }} #{{ membro[0] }}</h4>
              <h5>Email: {{ membro[3] }}</h5>
              <h5>Cargo: {{ membro[4] }}</h5>

              {% if membro[4] != 'administrador' and admin_id ==
              session["user_id"] %}
              <div id="radio" class="hidden">
                <form action="/alterar_cargo" method="POST">
                  <input type="hidden" name="user_id" value="{{ membro[0] }}" />
                  <input
                    type="hidden"
                    name="equipe_id"
                    value="{{ equipe[0] }}"
                  />
                  <label>
                    <input type="radio" name="novo_cargo" value="membro" {% if
                    membro[4] == 'membro' %}checked{% endif %}> Membro
                  </label>
                  <label>
                    <input type="radio" name="novo_cargo" value="moderador" {%
                    if membro[4] == 'moderador' %}checked{% endif %}> Moderador
                  </label>

                  <div id="button-alter" class="hidden">
                    <button
                      type="button"
                      id="button-cancel"
                      onclick="close_cargo()"
                    >
                      Cancelar
                    </button>
                    <button type="submit" class="button-edit">Salvar</button>
                  </div>
                </form>
              </div>
              <button
                id="button-editar"
                class="button-edit"
                onclick="show_cargo()"
              >
                Editar
              </button>
              {% endif %}
            </div>
            {% endfor %}
          </div>

          {% if cargo_user != "membro" %}
          <div class="form-box hidden" id="form-box">
            <div class="lado1">
              <img
                src="{{ url_for('static', filename='icons/add+user.svg') }}"
                id="add-user-image"
                alt="Adicionar Usuário"
              />
            </div>
            <div class="lado2">
              <form
                action="{{ url_for('main.invite_to_team_route', team_id=equipe[0]) }}"
                method="POST"
              >
                <div class="title">Convidar Membro</div>
                <div class="input-group">
                  <div class="input-box">
                    <input
                      type="text"
                      id="usernameOrEmail"
                      name="usernameOrEmail"
                      maxlength="80"
                      placeholder="Username ou Email do convidado:"
                    />
                  </div>
                  <div class="input-box">
                    <input
                      type="text"
                      name="mensagem"
                      id="mensagem"
                      placeholder="Mensagem para o convidado: (opcional)"
                      maxlength="255"
                    />
                  </div>
                  <button class="button" type="button" onclick="close_form()">
                    Cancelar
                  </button>
                  <button class="button" type="submit">Enviar Convite</button>
                </div>
              </form>
            </div>
          </div>
          {% endif %}
        </section>
      </main>
    </div>
  </body>
  <script src="{{ url_for('static', filename='js/team.js') }}"></script>
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</html>

app/templates/team/teams.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <title>DreamTeam - Equipes</title>
  </head>
  <body>
    {% include 'menu.html' %}

    <div class="container-top">
      <a href="/create_team"
        ><button class="button">Criar nova Equipe</button></a
      >
      <div class="flash.container">
        <!-- Mensagens Flash -->
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %}
        <ul class="flashes">
          {% for category, message in messages %}
          <li class="{{ category }}">{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %} {% endwith %}
      </div>

    </div>

    {% if equipes %}
    <div class="teams-container">
      {% for equipe in equipes %}
      <div class="equipe-box">
        <img class="equipe-foto" src="static/icons/noFoto.svg" alt="" />
        <h3 class="equipe-nome">{{ equipe[1] }}</h3>
        <p class="equipe-text">Membros: {{ equipe[4] }} membros</p>
        <p class="equipe-text">Cargo: {{ equipe[6] }}</p>
        <h4 class="equipe-txt">Projetos</h4>
        {% if equipe[5] %}
        <ul>
          <p class="equipe-text">{{ equipe[5] }} Projetos</p>
        </ul>
        {% else %}
        <p class="equipe-txt">Nenhum projeto foi criado ainda.</p>
        {% endif %}
        <div class="equipe-buttons">
          <a href="{{url_for('main.team_vision_route', team_id=equipe[0])}}">
            <button class="button">Ver Equipe</button>
          </a>
        </div>
      </div>

      {% endfor %}
    </div>
    {% else %}
    <h1>Nenhuma equipe encontrada. Crie sua primeira equipe</h1>
    {% endif %}
  </body>

  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</html>