app/routes/routes.py
from flask import Blueprint
from app.controllers.views import *

bp = Blueprint("main", __name__)

#! Index
@bp.route("/")
@bp.route("/index")
def index_route():
    return index()

#! Register
@bp.route("/register", methods=["GET", "POST"])
def register_route():
    return register()

#! Login
@bp.route("/login", methods=["GET", "POST"])
def login_route():
    return login()

#! Logout
@bp.route("/logout")
def logout_route():
    return logout()

#! Dashboard
@bp.route("/dashboard", methods=["GET"])
def dashboard_route():
    return dashboard()


#! Tela da Equipe
@bp.route("/team_vision/<int:team_id>")
def team_vision_route(team_id):
    return team_vision(team_id)
# equipe
@bp.route("/teams")
def teams_route():
    return teams()

#! Team
@bp.route("/create_team", methods=["GET", "POST"])
def create_team_route():
    return create_team()

#! Convidar Membros para o time
@bp.route("/invite_to_team/<int:team_id>", methods=["POST"])
def invite_to_team_route(team_id):
    return invite_to_team(team_id)

#! Aceitar o convite para equipe
@bp.route("/accept_invite", methods=["POST"])
def accept_invite_route():
    return accept_invite()

#! Recusar o convite para equipe
@bp.route("/decline_invite", methods=["POST"])
def decline_invite_route():
    return decline_invite()

#! Recusar o convite para equipe
@bp.route("/alterar_cargo", methods=["POST"])
def alterar_cargo_route():
    return alterar_cargo()

#! Enviar Mensagem
@bp.route("/adicionar_mensagem/<int:team_id>", methods=["POST"])
def adicionar_mensagem_route(team_id):
    return adicionar_mensagem(team_id)

@bp.route("/criar_projeto/<int:team_id>", methods=["GET", "POST"])
def criar_projeto_route(team_id):
    return create_project(team_id)

@bp.route('/criar_tarefa', methods=['POST'])
def criar_tarefa_route():
    return criar_tarefa()

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="static/css/style.css" />
    <title>Dashboard - {{session["user_username"]}}</title>
  </head>
  <body>
    {% include 'menu.html' %}

    <div class="container-top">
      <div class="flash.container">
        <!-- Mensagens Flash -->
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %}
        <ul class="flashes">
          {% for category, message in messages %}
          <li class="{{ category }}">{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %} {% endwith %}
      </div>
    </div>

    {% if convites %} {% if quantidade == 1 %}
    <li id="alert-invite" onclick="show_invite()">
      {{quantidade}} Novo convite de equipe
    </li>
    {% else %}
    <li id="alert-invite" onclick="show_invite()">
      {{quantidade}} Novos Convites de equipe
    </li>
    {% endif %}

    <div class="invite-card hidden">
      {% for convite in convites %}
      <h3>Equipe: {{ convite[3] }}</h3>
      <h5>Enviado por {{ convite[4] }} - {{ convite[5] }}</h5>
      <h5>{{ convite[2] }}</h5>
      <h5>Mensagem: {{ convite[1] }}</h5>
      <div class="buttons">
        <form action="{{url_for('main.accept_invite_route')}}" method="POST">
          <input type="hidden" name="invite_id" value="{{convite[0]}}" />
          <button class="button" type="submit">Aceitar</button>
        </form>

        <form action="{{url_for('main.decline_invite_route')}}" method="POST">
          <input type="hidden" name="invite_id" value="{{convite[0]}}" />
          <button class="button" type="submit">Recusar</button>
        </form>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </body>
  <h1>Olá {{session["user_username"]}}</h1>
  <script src="static/js/script.js"></script>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="static/css/style.css" />
    <title>DreamTeam</title>
  </head>

  <body class="light-mode">
    <div class="background-ellipse"></div>
    <header class="menu-superior">
      <ul>
        <li>
          <img
            src="static/icons/DreamTeam.svg"
            class="logo"
            alt="logo do DreamTeam"
          />
        </li>
        <li><a href="#">Redes</a></li>
        <li><a href="#">Contato</a></li>
        <li><a href="#">Sobre nós</a></li>
        <li>
          <img
            src="static/icons/login.svg"
            height="20"
            alt="icone de login"
          /><a href="/login">Login</a>
        </li>
        <li>
          <img
            src="static/icons/register.svg"
            height="20"
            alt="icone de cadastro"
          />
          <a href="/register">Cadastro</a>
        </li>

        <li>
          <a href="#" id="theme-toggle" class="button-mode">
            <img
              src="static/icons/mode.svg"
              alt="Ícone de sol e lua"
              height="25"
          /></a>
        </li>
      </ul>
    </header>
    <div class="container">
      <div class="ladoImg">
        <img src="static/icons/index.svg" alt="" />
      </div>
      <div class="ladoContent">
        <div class="title-index">
          <h1>Bem vindo ao Dream</h1>
          <h1 class="TeamTx">Team</h1>
          <h1>!</h1>
        </div>
        <div class="text-box">
          <h4>
            Nossa plataforma foi criada para ajudar equipes a organizar,
            gerenciar e colaborar em projetos com eficiência e praticidade.
          </h4>
          <h4>
            Seja uma startup, um novo empreendimento ou uma equipe criativa,
            aqui você encontra todas as ferramentas para levar suas ideias ao
            próximo nível
          </h4>
        </div>
        <div class="buttons-box">
          <a href="/login">
            <button class="button">
              Entrar
              <img
                src="static/icons/login.svg"
                height="20"
                alt="icone de login"
              /></button
          ></a>
          <a href="/register">
            <button class="button">
              Criar uma conta
              <img
                src="static/icons/register.svg"
                height="20"
                alt="icone de cadastro"
              /></button
          ></a>
        </div>
      </div>
    </div>
  </body>

  <script src="static/js/script.js"></script>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/css/style.css">
    <title>DreamTeam - Login</title>
</head>
<body>
    <header class="menu-superior">
        <ul>
            <div class="logo">
            <li><a href="/index"><img src="static/icons/DreamTeam.svg" class="logo" alt="logo do DreamTeam"></a></li>
        </div>
            <li>
                <div class="text-mode">
                Não tem uma conta? <a href="/register"> Faça cadastro</a><img src="static/icons/register.svg" height="20" alt="icone de login">
            </li>
            <li> <a href="#" id="theme-toggle" class="button-mode">
                    <img src="static/icons/mode.svg" alt="Ícone de sol e lua" height="25"></a></li>
                    </div>
        </ul>
    </header>

    <div class="container">
        <div class="ladoImg">
        <img src="static/icons/login-woman.svg" alt="">
        </div>
        <div class="ladoContent">
            <div class="form-box">
                <form class="formulario" action="/login" method="POST">
                    <div class="title">Bem vindo de volta!</div>
                                                <!-- Mensagens Flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <ul class="flashes">
            {% for category, message in messages %}
            <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
                    <div class="input-group">
                        <div class="input-box">
                            <input type="email" id="email" name="email" placeholder="E-mail:" maxlength="80" required>
                        </div>
                        <div class="input-box">
                            <input type="password" id="password" name="password" placeholder="Senha:" maxlength="30" required>
                        </div>
                        <div class="form-text">
                            <p>Não tem uma conta? <a href="/register">Cadastre-se já</a></p>
                            <p><a href="#">Esqueceu sua senha?</a></p>
                        </div>
                    </div>
                    <div class="button-form">
                        <button class="button">Continuar</button>
                    </div>
                </form>             
            </div>
        </div>
    </div>

</body>
<script src="static/js/script.js"></script>
</html>

app/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header class="menu-superior">
        <ul>
            <div class="logo">
            <li><a href="/dashboard"><img src="{{ url_for('static', filename='icons/DreamTeam.svg') }}" class="logo" alt="logo do DreamTeam"></a></li>
        </div>
        <li class="li-menu"><img src="{{ url_for('static', filename='icons/team.svg') }}" height="20" alt="icone de time"><a href="/teams">Equipes</a></li>
        <li class="li-menu"><img src="{{ url_for('static', filename='icons/abraco.svg') }}" height="20" alt="dois bonecos se abraçando"><a href="#">Amigos</a></li>
        <li class="li-menu"><img src="{{ url_for('static', filename='icons/perfil.svg') }}" height="20" alt="icone perfil"><a href="#">Perfil</a></li>
        <li class="li-menu"><img src="{{ url_for('static', filename='icons/sair.svg') }}" height="20" alt="icone sair"><a href="/logout">Sair</a></li>
            <li> <a href="#" id="theme-toggle" class="button-mode">
                    <img src="{{ url_for('static', filename='icons/mode.svg') }}" alt="Ícone de sol e lua" height="25"></a></li>
                    </div>
        </ul>
    </header>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/css/style.css">
    <title>DreamTeam - Cadastro</title>
</head>
<body>
    <header class="menu-superior">
        <ul>
            <div class="logo">
            <li><a href="/index"><img src="static/icons/DreamTeam.svg" class="logo" alt="logo do DreamTeam"></a></li>
        </div>
            <li>
                <div class="text-mode">
                Já tem uma conta? <a href="/login"> Faça login</a><img src="static/icons/login.svg" height="20" alt="icone de login">
            </li>
            <li> <a href="#" id="theme-toggle" class="button-mode">
                    <img src="static/icons/mode.svg" alt="Ícone de sol e lua" height="25"></a></li>
                    </div>
        </ul>
    </header>

    <div class="container">
        <div class="ladoContent">
            <div class="form-box">
                <form  class="formulario" action="/register"  method="POST">
                    <div class="title">Registre-se</div>
                            <!-- Mensagens Flash -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <ul class="flashes">
            {% for category, message in messages %}
            <li class="{{ category }}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
                    <div class="input-group">
                        <div class="input-box">
                            <input type="text" id="nome" name="nome" placeholder="Seu Nome:" required maxlength="32">
                        </div>
                        <div class="input-box">
                            <input type="text" id="username" name="username" placeholder="Username:" required maxlength="32">
                        </div>
                        <div class="input-box">
                            <input type="email" id="email" name="email" placeholder="E-mail:" maxlength="80" required>
                        </div>
                        <div class="input-box">
                            <input type="password" id="password" name="password" placeholder="Senha:" maxlength="30" required>
                        </div>
                    
                    <div class="input-box">
                        <input type="password" id="confirmPassword" name="confirmPassword" placeholder="Confirme sua senha:" required>
                    </div>
                </div>
                    <button class="button" type="submit">Criar Conta</button>
                </form>
                </div>

                    </div>
                


        <div class="ladoImg">
            <img src="static/icons/register-woman.svg" alt="">
        </div>
    </div>

</body>
<script src="static/js/script.js"></script>
</html>